@extends('laradoc::layouts.app')

@section('content')
    @php
        $title = $documentation['title'] ?? ucfirst($module);
        $description = $documentation['description'] ?? '';
    @endphp

    <div class="d-flex justify-content-between align-items-center mb-4">
        <div>
            <h1 class="h2 mb-1">{{ $title }}</h1>
            @if($description)
                <p class="text-muted mb-0">{{ $description }}</p>
            @endif
        </div>
        <div class="btn-group" role="group">
            <button type="button" class="btn btn-outline-primary laradoc-edit-toggle">
                <i class="bi bi-pencil"></i> Edit
            </button>
            <button type="button" class="btn btn-outline-secondary" onclick="window.print()">
                <i class="bi bi-printer"></i> Print
            </button>
        </div>
    </div>

    <div class="laradoc-content">
        @if($documentation && isset($documentation['content']))
            <div class="markdown-content">
                {!! marked($documentation['content']) !!}
            </div>
        @else
            <div class="text-center py-5">
                <i class="bi bi-file-text display-1 text-muted"></i>
                <h3 class="mt-3">No Documentation Available</h3>
                <p class="text-muted">This module doesn't have any documentation yet.</p>
                <button class="btn btn-primary" onclick="generateDocumentation('{{ $module }}')">
                    <i class="bi bi-magic"></i> Generate Documentation
                </button>
            </div>
        @endif
    </div>

    <div class="laradoc-editor" style="display: none;">
        <form id="editForm" method="POST" action="{{ route('laradoc.update', $module) }}">
            @csrf
            <div class="mb-3">
                <label for="content" class="form-label">Documentation Content (Markdown)</label>
                <textarea 
                    id="content" 
                    name="content" 
                    class="form-control" 
                    rows="20" 
                    style="font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace;"
                >{{ $documentation['content'] ?? '' }}</textarea>
                <div class="form-text">
                    Use Markdown syntax for formatting. 
                    <a href="https://www.markdownguide.org/basic-syntax/" target="_blank">Markdown Guide</a>
                </div>
            </div>
            <div class="d-flex gap-2">
                <button type="submit" class="btn btn-primary">
                    <i class="bi bi-check"></i> Save Changes
                </button>
                <button type="button" class="btn btn-secondary laradoc-edit-toggle">
                    <i class="bi bi-x"></i> Cancel
                </button>
            </div>
        </form>
    </div>

    @if($documentation && isset($documentation['metadata']))
        <div class="mt-4">
            <h4>Module Information</h4>
            <div class="row">
                @if(isset($documentation['metadata']['last_updated']))
                    <div class="col-md-6">
                        <strong>Last Updated:</strong> 
                        {{ \Carbon\Carbon::parse($documentation['metadata']['last_updated'])->format('M j, Y g:i A') }}
                    </div>
                @endif
                @if(isset($documentation['metadata']['generated_by']))
                    <div class="col-md-6">
                        <strong>Generated By:</strong> {{ $documentation['metadata']['generated_by'] }}
                    </div>
                @endif
            </div>
        </div>
    @endif

    <script>
        function generateDocumentation(module) {
            if (confirm('Generate documentation for this module?')) {
                window.location.href = `{{ route('laradoc.generate') }}?module=${module}`;
            }
        }
    </script>
@endsection 